### ISSUE TITLE
ClassNotFoundException: com.plaid.link.networking.NetworkLostWorker

### ISSUE THREAD

**Issue by martymiller** [plaid/plaid-link-android#201] opened 2021-10-11 18:14 UTC
We recently updated from 1.3.0 to version 3.6.0 and are seeing crash reports in Firebase from our DaggerWorkerFactory.  What usually happens is when a user updates the app, there will be a crash if the class in the worker thread doesn't match the class in the current code base.

Did this class get removed recently (or maybe moved to a different package)?  I can't find any documentation.

**Comment by JeroenMols** [comment] 2021-10-12 09:12
Hi @martymiller,

We removed the `NetworkLostWorker` in Link SDK v `1.3.1` because it created some unintended side effects. This is functionality that has been removed, so there is no replacement class for this.

It seems like we didn't handle that deprecation case thoughtfully enough, we should have ensured to cancel all `NetworkLostWorker` or maybe even keep an empty work class indefinitely. Apologies for that and thanks for bringing this to our attention.

To mitigate the crash you are seeing, you can either:
- create a no-operation `NetworkLostWorker` class yourself:

```
package com.plaid.link.networking

class NetworkLostWorker(
  private val context: Context,
  workerParams: WorkerParameters
) :
  Worker(context, workerParams) {

  override fun doWork(): Result = Result.success()

}

```

- cancel all previous work at application startup (might still have race conditions): `workManager.cancelAllWorkByTag("no_network")`
- ignore these crashes if they are non fatal

Out of curiosity, are these crashes fatal? or informative?

Hope this helps

**Comment by martymiller** [comment] 2021-10-12 17:27
Hi @JeroenMols.  To be fair, we were upgrading from a very old version to the latest.  Yes, these crashes are fatal, so many users are seeing the app crash on startup.  And restarting the app doesn't fix it since the worker is still running.  We will implement the suggestions you provided.  Thank you!

**Comment by JeroenMols** [comment] 2021-11-02 09:57
@martymiller do you have any insights on whether or not the suggestion fixed your problem?

**Comment by sonalagarwal** [comment] 2021-11-05 20:13
Yes, this fixed our problem. Is there a latest version we can use where we can remove this workaround?

**Comment by JeroenMols** [comment] 2021-11-10 13:44
Thanks for letting us know.

We're unfortunately not going to add a fix for this, given that the root cause was introduced on a very old Link version `1.3.1` and we haven't see any bug reports of that up to now.

We understand that that might not be the outcome you were looking for, but we are taking this learnings along in our future SDK updates. In fact you even prevented us from making the same mistake again in our last release.

Thank you very much for bringing this to our attention!

**Closed by JeroenMols** 2021-11-10 13:44 UTC

**Comment by sonalagarwal** [comment] 2021-11-10 15:25
Thanks for letting us know. We are using 3.6.0 version where the issue occurred.

**Comment by JeroenMols** [comment] 2021-11-12 08:52
To clarify my earlier comment: this only happens when upgrading from a Link version older than `1.3.1` to a more recent Link version.
