### ISSUE TITLE
Reconnect flow crashes in SDK 1.0.1

### ISSUE THREAD

**Issue by patber** [plaid/plaid-link-android#38] opened 2020-02-21 10:49 UTC
We're unable to complete the Reconnect flow for product PlaidProduct.AUTH with the sample app, using SDK 1.0.1. 
```
      Plaid.openLink(
        activity = this,
        linkConfiguration = LinkConfiguration(
          clientName = "Test App",
          products = listOf(PlaidProduct.AUTH),
          publicToken = "public-sandbox-bc8ece47-37a8-49c2-9ca1-a762330fd3ee"
        ),
        requestCode = LINK_REQUEST_CODE
      )

```

When the success screen "Your account has been reconnected" shows and clicking "Continue" button, the app crashes, before returning to app:
```
2020-02-21 11:36:02.895 12048-12048/com.plaid.linksample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.plaid.linksample, PID: 12048
    java.lang.IllegalStateException: Gson().fromJson<List<Lin…t>>() {}.type
              ) must not be null
        at com.plaid.linkbase.internal.LinkUrlParser.parseSuccess(LinkUrlParser.kt:130)
        at com.plaid.linkbase.internal.LinkUrlParser.parseUrlString(LinkUrlParser.kt:60)
        at com.plaid.linkwebview.LinkWebviewPresenter.parseWebviewResponse(LinkWebviewPresenter.kt:47)
        at com.plaid.linkwebview.PlaidWebClient.shouldOverrideUrlLoading(WebViewClients.kt:75)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

**Comment by amytang0** [comment] 2020-02-21 17:43
Hi, are you seeing Error in the title of the "Success" screen?
![adbscreen](https://user-images.githubusercontent.com/863461/75057740-86b01f80-548e-11ea-8da9-bf90d415f2d7.png)

**Comment by patber** [comment] 2020-02-21 18:43
No, I see "Success".
![image](https://user-images.githubusercontent.com/7654443/75062005-319df900-54e2-11ea-8d6d-eef2a253e8b3.png)

**Comment by amytang0** [comment] 2020-02-24 16:43
Hi, can you send me the access_token you are using? For the one you first posted, I see an "invalid credentials" error was returned

**Comment by patber** [comment] 2020-02-24 18:58
I'm not sure what you mean with `access_token` ? I provided the `public_token` in my first post. Here is a new one: `public-sandbox-83f928d0-d017-4171-a027-5093aa34ae4a`.

Can you reproduce this problem with your own project? Can it be that I didn't configure proper webredirectUrl, and/or android package names?

**Comment by amytang0** [comment] 2020-02-25 03:03
Unfortunately we can not repro this. Are you calling `https://sandbox.plaid.com/item/public_token/exchange` and `https://sandbox.plaid.com/item/public_token/create`? You have to exchange the `public_token`that you get with the first LinkClientGetResponse for an `access_token` (with the first API call), and create an update `public_token` with the second API call. This `public_token` is different from the first `public_token`.

You will also need to make sure the Item is in an error state first before updating: plaid.com/docs/#simulating-item_login_required-errors.

**Comment by patber** [comment] 2020-02-25 20:36
Hi,
yes, we're exchanging the tokens.

Since the used `public_token` opens the Plaid widget properly in "reconnect mode" with the actual institution's login screen, and after completing the flow the widget reports "Success, your account has been  reconnected", our token exchange flow must be correct?

I think there are two possible reasons for the crash:

1. We are missing some configuration on the Plaid dashboard. The stacktrace indicates an (unexpected) empty list of some internal type
 ```
Process: com.plaid.linksample, PID: 12048
    java.lang.IllegalStateException: Gson().fromJson<List<Lin…t>>() {}.type
              ) must not be null
        at com.plaid.linkbase.internal.LinkUrlParser.parseSuccess(LinkUrlParser.kt:130)
        at com.plaid.linkbase.internal.LinkUrlParser.parseUrlString(LinkUrlParser.kt:60)
        at com.plaid.linkwebview.LinkWebviewPresenter.parseWebviewResponse(LinkWebviewPresenter.kt:47)
```
I have tried to add/delete Redirect URIs, and Android package names, without success. Are they needed, and is there any other config needed?

2. When reproducing this reconnect scenario with the Plaid Link Sample app, clicking on "Continue" button on the success screen the app is actually crashed and restarted, since the main screen is empty and not reporting the results in `onActivityResult`.
Can you confirm that `onActivityResult` was invoked when you tried to reproduce this scenario?

**Comment by amytang0** [comment] 2020-02-27 00:54
Hi, can you upgrade to 1.0.2? We added some extra diagnostics to crashes that might help us fix the problem

**Comment by patber** [comment] 2020-02-28 17:51
Hi,
yes, I use user_good/pass_good for sandbox credentials.

I have now tried 1.0.2 version. I also attach my logcat file for this session.
[logcat.txt](https://github.com/plaid/plaid-link-android/files/4268350/logcat.txt)

**Comment by zsweigart** [comment] 2020-03-11 00:42
Hi @patber we have just released a fix for this 1.0.3

**Comment by patber** [comment] 2020-03-12 16:49
Hi,
I have tried with 1.0.3 now and it has resolved the crash within the SDK, so now it calls 
onActivityResult() properly.

But, I now experience a weird behaviour: the returned `linkConnectionMetadata` contains no accounts list when running the SDK in default/English language, but an accurate list is returned when using Spanish language. We're supposed to get the account list in onSuccess, right? See these logs: [plaid-1.0.3-reconnect-responses.txt](https://github.com/plaid/plaid-link-android/files/4325457/plaid-1.0.3-reconnect-responses.txt)

**Comment by zsweigart** [comment] 2020-03-13 19:50
Hi @patber I am unable to reproduce the issue, can you send the two configurations you are using to open link (don't forget to redact your keys)?

**Closed** 2020-03-13 19:56 UTC
