### ISSUE TITLE
Crash report by Firebase

### ISSUE THREAD

**Issue by leiiiooo** [plaid/plaid-link-android#129] opened 2021-01-19 00:03 UTC
# The problem

In multiple iterations of our App, it has been consistently found that Plaid SDK has been having Crash, and the problem has been found in the version currently in use as follows, with details below.

# Environment

|                           |                                  |
| :-----------------------: | :------------------------------: |
|    plaid link sdk-core    |              3.2.1               |
|    Android OS Version     | Android 10, Android 9, Android 7 |
| Android Devices/Emulators |        Samaung, LGE, TCL         |

# Logs

```java
Caused by kotlin.UninitializedPropertyAccessException: lateinit property component has not been initialized
       at com.plaid.link.Plaid.getComponent$link_sdk_web_release(Plaid.java:1)
       at com.plaid.link.internal.LinkActivity.onCreate(LinkActivity.java:2)
       at android.app.Activity.performCreate(Activity.java:7866)
       at android.app.Activity.performCreate(Activity.java:7855)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3273)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3437)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
```

**Comment by JeroenMols** [comment] 2021-01-27 15:35
Duplicate of https://github.com/plaid/plaid-link-android/issues/122

Upgrading to `3.2.2` solves another occurrence. Closing this issue and tracking progress in https://github.com/plaid/plaid-link-android/issues/122.

**Closed by JeroenMols** 2021-01-27 15:35 UTC
