### ISSUE TITLE
Plaid 3.3.1 integration

### ISSUE THREAD

**Issue by barisbingor** [plaid/plaid-link-android#166] opened 2021-05-20 09:24 UTC
Hi, I am trying to implement the 3.x Plaid version but when I try to upgrade to 3.3.1, I see the following trace log with a failure. What exactly am I supposed to do in this case? I thought this was fixed with 3.2.6

> Execution failed for task ':xxxxxx:generateDebugRFile'.
> Could not resolve all files for configuration ':xxxxxx:debugCompileClasspath'.
   > Could not resolve pro.streem.pbandk:pbandk-runtime:0.10.0.
     Required by:
         project :xxxxxx
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'. However we cannot choose between the following variants of pro.streem.pbandk:pbandk-runtime:0.10.0:
          - debugApiElements-published
          - debugRuntimeElements-published
          - jvmApiElements-published
          - jvmRuntimeElements-published
        All of them match the consumer attributes:
          - Variant 'debugApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'debug' but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but the consumer didn't ask for it
          - Variant 'debugRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'debug' but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but the consumer didn't ask for it
          - Variant 'jvmApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares an API of a component:
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but the consumer didn't ask for it
          - Variant 'jvmRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares a runtime of a component:
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but the consumer didn't ask for it
        The following variants were also considered but didn't match the requested attributes:
          - Variant 'iosArm64ApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'iosX64ApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'jsApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'jsRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-runtime' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'linuxX64ApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'macosX64ApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'metadataApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'releaseApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'
          - Variant 'releaseRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'
   > Could not resolve pro.streem.pbandk:pbandk-runtime:0.10.0.
     Required by:
         project :xxxxxx > com.plaid.link:sdk-core:3.3.1
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'. However we cannot choose between the following variants of pro.streem.pbandk:pbandk-runtime:0.10.0:
          - debugApiElements-published
          - debugRuntimeElements-published
          - jvmApiElements-published
          - jvmRuntimeElements-published
        All of them match the consumer attributes:
          - Variant 'debugApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'debug' but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but the consumer didn't ask for it
          - Variant 'debugRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'debug' but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but the consumer didn't ask for it
          - Variant 'jvmApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares an API of a component:
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but the consumer didn't ask for it
          - Variant 'jvmRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares a runtime of a component:
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but the consumer didn't ask for it
        The following variants were also considered but didn't match the requested attributes:
          - Variant 'iosArm64ApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'iosX64ApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'jsApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'jsRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-runtime' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'linuxX64ApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'macosX64ApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'metadataApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'releaseApiElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'
          - Variant 'releaseRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime:0.10.0 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'

My gradle file is like this

     apply plugin: 'com.android.library'

    android {

    defaultPublishConfig 'release'

    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {

        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion

        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
            debuggable true
        }
        internal.initWith(buildTypes.release)
    }
    buildToolsVersion rootProject.ext.buildToolsVersion
    }

**Comment by zsweigart** [comment] 2021-05-20 14:30
A potential issue is if you are using dependencies that are kotlin multiplatform.  In that case you can resolve kapt subproject dependencies to java runtime
```
subprojects { subProject ->
    subProject.configurations.all { configuration ->
        // Workaround for kapt bug with MPP dependencies
        // https://youtrack.jetbrains.com/issue/KT-31641
        // https://youtrack.jetbrains.com/issue/KT-33206
        if (name.contains('kapt')) {
            attributes.attribute(Usage.USAGE_ATTRIBUTE, subProject.objects.named(Usage.class, Usage.JAVA_RUNTIME))
        }
    }
}
```

See this issue for more details https://youtrack.jetbrains.com/issue/KT-31641

Closing as duplicate of https://github.com/plaid/plaid-link-android/issues/160

**Closed by zsweigart** 2021-05-20 14:30 UTC
