### ISSUE TITLE
IllegalStateException on Plaid.OpenLink

### ISSUE THREAD

**Issue by ahclipse** [plaid/plaid-link-android#127] opened 2021-01-11 18:47 UTC
Hey Team! 

# The problem

We intermittently receiving an `IllegalStateException` when launching the `Plaid.openLink` flow.

We had a [similar issue appear a few months ago](https://github.com/plaid/plaid-link-android/issues/71) which we resolved by updating the library version and reregistering the Android package name in the online dashboard. 

This is experienced in the `2.2.0` library version; we are currently working on updating to `3.2.2` but were wondering if there was root cause to this problem that we could address? Our monitoring shows this first appeared on 12/6/20 with an increase in occurrences since. 

# Environment

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | 11.0 (30)                |
| Android Devices/Emulators    | Pixel 4 emulator                |

- This is a sample device but we have been experiencing this on a variety of devices and OS versions. 

# Steps to Reproduce

Launch Plaid connection flow via `Plaid.openLink(activity, config)`

Here is a sample config that exhibits this issue 

```
LinkTokenConfiguration(token=link-production-bfe343f3-4065-4f6b-bee4-174932fb62f2, logLevel=ASSERT, extraParams={})
```

# Logs
EDIT: This token seems to be throwing a `PlaidLinkConfigurationMalformedLinkTokenException` 

<details>
    <summary> Stack Trace </summary>

```
01-06 16:59:54.471  3276  3276 I Layer   : id=3758 onRemoved Surface(name=AppWindowToken{2284e84 token=Token{bd5cc97 ActivityRecord{5befb16 u0 com.ibotta.android/.mvp.ui.activity.account.withdraw.WithdrawActivity t14}}})/@0x6688c08 - animation-leash#0
01-06 16:59:54.471  3276  3276 I Layer   : id=3759 onRemoved Surface(name=AppWindowToken{384a8fa token=Token{f95cf25 ActivityRecord{f76571c u0 com.ibotta.android/com.plaid.link.internal.LinkActivity t14}}})/@0x5db8438 - animation-leash#0
01-06 16:59:54.474 21665 21665 E s4$d    : java.lang.IllegalStateException:
01-06 16:59:54.474 21665 21665 E s4$d    : 	at com.plaid.internal.s4$f.accept(SourceFile:16)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at io.reactivex.internal.operators.single.SingleDoOnEvent$DoOnEvent.onSuccess(SingleDoOnEvent.java:55)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at android.os.Handler.handleCallback(Handler.java:873)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at android.os.Looper.loop(Looper.java:214)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at android.app.ActivityThread.main(ActivityThread.java:7073)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at java.lang.reflect.Method.invoke(Native Method)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
01-06 16:59:54.474 21665 21665 E s4$d    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

</details>

Any insight would be much appreciated!

**Comment by amytang0** [comment] 2021-01-11 23:03
Hey, sorry about that! The root cause is fixed in 3.2.2 (proguard issue we missed around our PlaidEnvironment). Please reopen if this recurs in 3.2.2

**Closed** 2021-01-11 23:26 UTC
