### ISSUE TITLE
oauth - no redirect even if I have Chrome browser installed

### ISSUE THREAD

**Issue by slavamarchenkokrasov** [plaid/plaid-link-android#228] opened 2022-06-14 15:50 UTC
# The problem
No redirect is happening on Continue button press in oauth flow. I have Chrome installed

# Environment

Xioami Redmi Note 9, Android Emulator Pixel 5 with Chrome
Plaid SDK 3.10.

# Steps to Reproduce

1. Generate plaid link token with curl
2. Open plaid Link with this token
3. Select Platypus OAUTH bank
4. Select Platypus OAUTH bank again - see "Authenticate with Platypus OAUTH bank" screen with 3 steps
5. Click Continue
6. Screen with Blue "Continue" buttons is shown where you cannot do anything.

# Expected Result
App show be redirected to web-view to perform aouth pseudo authorization

# Logs
No relevant logs are in the console, no warning or errors

**Comment by RajDevWilson** [comment] 2022-10-26 07:28
Same here. Any solution?

**Comment by oxied** [comment] 2023-01-12 10:56
https://plaid.com/docs/link/android/troubleshooting/#no-redirect-back-to-app

**Comment by FAStstorebitbankuk** [comment] 2023-02-24 22:23
Redirect is not working

**Comment by phoenixy1** [comment] 2024-12-24 04:04
Closing this due to inability to reproduce / lack of information on what troubleshooting steps were followed and being filed on a very old version of the SDK. If this comes back, feel free to re-open.

**Closed by phoenixy1** 2024-12-24 04:04 UTC
