### ISSUE TITLE
Captcha screen does not disappear completely

### ISSUE THREAD

**Issue by LukaFinzgar** [plaid/plaid-link-android#80] opened 2020-06-24 12:40 UTC
When i try to connect with e.g. paypal, i need to solve captcha. 
When i press "verify", the captcha images goes off the screen just halfway. I need to click somewhere else for it to disappear completely.

**Comment by zsweigart** [comment] 2020-06-24 16:42
Hi @LukaFinzgar thanks for this report.  The current iteration of the SDK uses a webview to display Link.  We have run into several issues with recaptcha being cutoff in webviews and we have opened an issue on the Google recaptcha project https://github.com/google/recaptcha/issues/334.  

Could you provide more information on what device(s) you are seeing this on, how often it is reproducible, and the exact steps to reproduce, and a screenshot of the result?

Thanks!

**Comment by LukaFinzgar** [comment] 2020-06-29 11:13
Hi.
I checked the ticket you opened on google and it looks like i have the same problem.
I tested on Xiaomi mi9t and Samsung Galaxy S6.

It happens every time when i try to connect with Paypal. 
Sometimes i can dismiss the captcha images by clicking somewhere else on the screen (if captcha challenge has been solved, screenshot 1), in other cases i cant even press "verify" button (screenshot 2).

![image](https://user-images.githubusercontent.com/45970522/85997676-18660580-ba0a-11ea-9afc-912dd4a0f6a9.png)

![image](https://user-images.githubusercontent.com/45970522/85997692-1c922300-ba0a-11ea-8417-af0b15ad30ed.png)

**Comment by zsweigart** [comment] 2020-07-02 00:20
Hi @LukaFinzgar, thanks for the info.  I have only been able to reproduce once.  Could you provide the version of the webview?  For Android > 7 you can use this code to get it.
```
      try {
        val webViewFactory = Class.forName("android.webkit.WebViewFactory")
        val method: Method = webViewFactory.getMethod("getLoadedPackageInfo")
        Log.i("VERSION",  (method.invoke(null) as PackageInfo).versionName)
      } catch (e: java.lang.Exception) {
        e.printStackTrace()
      }
```

Considering this is a webview with a known recaptcha issue there may not be much we can do for now but we are working on a native (non-webview) version that should help us fix as well too.

**Comment by LukaFinzgar** [comment] 2020-07-02 07:28
Calling "(method.invoke(null) as PackageInfo).versionName" throws exception:
"null cannot be cast to non-null type android.content.pm.PackageInfo".

I tried with "WebView.getCurrentWebViewPackage().versionName" and i got:
83.0.4103.106

Hope it helps you.

**Comment by JeroenMols** [comment] 2020-09-01 18:56
Thank you for filing this issue.

We are closing it on this project as this seems to be a Google recaptcha issue. Once google/recaptcha#334 is addressed, we will upgrade our backend and the fix should propagate to the Android SDK.

**Closed by JeroenMols** 2020-09-01 18:56 UTC
